### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-external-assets#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/external-assets/1) criteria:
- [x] all the styles are in an external `.css` file that have a visible effect on the page
- [x] all the JavaScript is in an external `.js` file, with some behavioral effect on the page
- [x] return no errors (warnings are OK) when the HTML document is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] return no errors or warnings when contents of the CSS file are pasted into [CSS Lint](http://csslint.net/)
- [x] return no errors or warnings when the JavaScript is pasted into [JavaScript Lint](http://www.javascriptlint.com/online_lint.php)

**Comment by chrisvfritz** [comment]
I'm seeing [some validation errors](https://validator.w3.org/nu/?doc=http%3A%2F%2Fravedave.surge.sh%2F) for your HTML. Take a look at those and let me know if you have any questions.

**Comment by ackleyd1** [comment]
well my child elements of button aren't allowed so I got rid of div and then it told me p and most likely span aren't allowed either. Is there a way around this? It all works right :/

**Comment by ackleyd1** [comment]
Here i changed the function of the button

**Comment by chrisvfritz** [comment]
Great question! I'll give this the :shipit:, but here's how you could create something that looks like a button without it being a `button` _element_. For any element, including a link (`a` element), you could give it a class that contains button-like styles. For example:

``` html
<a href="https://google.com/" class="button">Go to Google!</a>
```

``` css
.button {
  background: #3498db;
  border-radius: 4px;
  color: #ffffff;
  font-size: 20px;
  padding: 10px 20px 10px 20px;
  text-decoration: none;
}

.button:hover {
  background: #3cb0fd;
  text-decoration: none;
}
```

Another advantage of this is the button is guaranteed to look similar in all browsers, rather than defaulting  to whatever `button` elements look like for that operating system.
